<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Alastair Wyse</Authors>
    <Description>Implementation of grids within the PowerGrid framework.</Description>
    <Copyright>Copyright © Alastair Wyse 2026.</Copyright>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerGrid.Core\PowerGrid.Core.csproj" />
  </ItemGroup>

</Project>
