<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Alastair Wyse</Authors>
    <Description>Classes which read and write Powergrid grids from and to persistent storage.</Description>
    <Copyright>Copyright © Alastair Wyse 2026.</Copyright>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ApplicationLogging" Version="2.0.0" />
    <PackageReference Include="ApplicationMetrics" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerGrid.Core\PowerGrid.Core.csproj" />
    <ProjectReference Include="..\PowerGrid.Grids\PowerGrid.Grids.csproj" />
  </ItemGroup>

</Project>
