<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Authors>Alastair Wyse</Authors>
    <Description>Classes which host PowerGrid components as a REST-based web API.</Description>
    <Copyright>Copyright © Alastair Wyse 2026.</Copyright>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="ApplicationLogging.Adapters.MicrosoftLoggingExtensions" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\PowerGrid.Persistence.SqlServer\PowerGrid.Persistence.SqlServer.csproj" />
  </ItemGroup>
  
</Project>
