<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Description>Unit tests for classes in the PowerGrid.Persistence namespace.</Description>
    <Copyright>Copyright © Alastair Wyse 2026.</Copyright>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerGrid.Core.UnitTests\PowerGrid.Core.UnitTests.csproj" />
    <ProjectReference Include="..\PowerGrid.Persistence\PowerGrid.Persistence.csproj" />
  </ItemGroup>

</Project>
