<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerGrid.Core.UnitTests\PowerGrid.Core.UnitTests.csproj" />
    <ProjectReference Include="..\PowerGrid.Grids\PowerGrid.Grids.csproj" />
    <ProjectReference Include="..\PowerGrid.Persistence.SqlServer\PowerGrid.Persistence.SqlServer.csproj" />
  </ItemGroup>

</Project>
